name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build firmware (PlatformIO)
        run: |
          pio run \
            -e Ebyte_EoRa-S3_Repeater_mqtt \
            -e Generic_E22_sx1262_repeater_mqtt \
            -e Generic_E22_sx1268_repeater_mqtt \
            -e Heltec_E213_repeater_mqtt \
            -e Heltec_E290_repeater_mqtt \
            -e Heltec_T190_repeater_mqtt \
            -e heltec_tracker_v2_repeater_mqtt \
            -e Heltec_v2_repeater_mqtt \
            -e Heltec_v3_repeater_mqtt \
            -e heltec_v4_repeater_mqtt \
            -e heltec_v4_tft_repeater_mqtt \
            -e Heltec_Wireless_Paper_repeater_mqtt \
            -e Heltec_Wireless_Tracker_repeater_mqtt \
            -e Heltec_WSL3_repeater_mqtt \
            -e LilyGo_T3S3_sx1262_repeater_mqtt \
            -e LilyGo_T3S3_sx1276_repeater_mqtt \
            -e LilyGo_TBeam_1W_repeater_mqtt \
            -e LilyGo_TDeck_repeater_mqtt \
            -e LilyGo_Tlora_C6_repeater_mqtt \
            -e M5Stack_Unit_C6L_repeater_mqtt \
            -e Meshadventurer_sx1262_repeater_mqtt \
            -e Meshadventurer_sx1268_repeater_mqtt \
            -e Meshimi_repeater_mqtt \
            -e nibble_screen_connect_repeater_mqtt \
            -e RAK_3112_repeater_mqtt \
            -e Station_G2_repeater_mqtt \
            -e T_Beam_S3_Supreme_SX1262_repeater_mqtt \
            -e Tbeam_SX1262_repeater_mqtt \
            -e Tbeam_SX1276_repeater_mqtt \
            -e ThinkNode_M2_Repeater_mqtt \
            -e ThinkNode_M5_Repeater_mqtt \
            -e WHY2025_badge_repeater_mqtt \
            -e Xiao_C6_repeater_mqtt \
            -e Xiao_S3_WIO_repeater_mqtt \
            -e DIY_ESP32S3_N16R8_E22_Back2back_repeater_mqtt 

      - name: Prepare build artifacts

        run: |
          mkdir -p out
          find .pio/build/ -name "firmware.bin" -exec sh -c 'cp "{}" "out/$(basename $(dirname "{}"))_firmware.bin"' \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*.bin
          generate_release_notes: true